# Macro to add the Unit Test to the project.
function(ADD_TESTS)
  unset(TEST_DIR)
  if(ARGC GREATER 0)
    set(TEST_DIR ${ARGV0})
  endif()
  if(NOT DEFINED TEST_DIR)
    set(TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/test")
  endif()
  if(IS_DIRECTORY ${TEST_DIR})
    if(EXISTS "${TEST_DIR}/CMakeLists.txt" AND NOT EXISTS "${TEST_DIR}/ignore.cmake")
      set(TEST_PROJECT_NAME "${PROJECT_NAME}Tests")
      set(CMAKE_FOLDER "TEST")
      message(STATUS "Configuring Unit Test directory: ${TEST_DIR}")
      add_subdirectory(${TEST_DIR})
    endif()
  endif()
endfunction()